43 add post endpoints to redux createapi
ImmiChat-V2/client pull request #47
Opened 2023-01-12 22:59 UTC by DLiSWE

2023-01-14 21:23 UTC, Matt-Tan15 submitted a review, later dismissed
looks good

2023-01-14 21:23 UTC, raylu511 approved these changes

2023-01-14 21:25 UTC, raylu511 commented on src/features/posts/models/Posts.model.ts
> +export type PostIdBodyProps = {
Should we also be able to update the media of the post?
Also the type name is weird.

2023-01-14 21:27 UTC, raylu511 commented on src/features/posts/models/Posts.model.ts
> +export type PostIdBodyProps = {
I would name this `UpdatePostRequestModel` instead.
And also type `postId `as a number.

2023-01-14 21:29 UTC, raylu511 requested changes
Did you test all of the endpoints out?

2023-01-14 22:38 UTC, DLiSWE commented
I did

2023-01-15 15:50 UTC, Matt-Tan15 commented on src/features/auth/components/LoginForm.tsx
> +import { useCreatePostMutation } from "features/posts/services/postApiSlice";
what is this used for on the LoginForm?

2023-01-15 16:03 UTC, DLiSWE commented on src/features/auth/components/LoginForm.tsx
> +import { useCreatePostMutation } from "features/posts/services/postApiSlice";
you right

2023-01-16 00:35 UTC, Matt-Tan15 approved these changes

2023-01-16 04:02 UTC, Matt-Tan15 commented on src/shared/components/SharePost.tsx
>  type SharePostProps = {
should we change this to SharePostPropType?

2023-01-23 19:59 UTC, closed without merging